    using System;

    namespace CosmosWizard.Web.AutoGeneratedFiles
    {
        public class Action
        {
            public class ParentRisk2
            {
                public string Title;
                public string Bucket;
                public string Shard;
                public string Id;
                public object Meta;
            }

            public class Items2
            {
                public string fullName;
                public string email;
            }

            public class Owner2
            {
                public Items2 Items;
                public string Id;
                public object Bucket;
                public object Shard;
                public object DisplayLabel;
            }

            public class Items3
            {
                public string fullName;
                public string email;
            }

            public class Assignee2
            {
                public Items3 Items;
                public string Id;
                public object Bucket;
                public object Shard;
                public object DisplayLabel;
            }

            public class Metadata
            {
            }

            public string id;
            public string _rid;
            public string _self;
            public int _ts;
            public string _etag;
            public string Shard;
            public int Seq;
            public string SiteId;
            public object Site;
            public string RiskItemId;
            public ParentRisk2 ParentRisk;
            public string Description;
            public DateTime DueDate;
            public DateTime ReminderDate;
            public string PriorityId;
            public string Priority;
            public string CategoryId;
            public string Category;
            public string StatusId;
            public string Status;
            public Owner2 Owner;
            public Assignee2 Assignee;
            public object ExternalReference;
            public DateTime CreatedDateTime;
            public DateTime LastUpdatedDateTime;
            public string CreatedByPersonId;
            public string CreatedByPersonName;
            public string LastUpdatedByPersonId;
            public string LastUpdatedByPersonName;
            public string Bucket;
            public bool IsActive;
            public int _lsn;
            public Metadata _metadata;

        }
    }
