using System;
using System.Collections.Generic;

namespace CosmosWizard.Web.AutoGeneratedFiles
{
    public class Person
    {
        public class Role
        {
            public string Value;
            public string Bucket;
            public string Shard;
            public string Id;
            public object Meta;
        }

        public class PersonSiteRelationship
        {
            public string SiteId;
            public bool AreaManager;
            public bool SiteManager;
        }

        public class Metadata
        {
        }

        public string id;
        public string _rid;
        public string _self;
        public int _ts;
        public string _etag;
        public string PersonReference;
        public string FirstName;
        public string LastName;
        public string PreferredName;
        public string BusinessTitle;
        public string EmailAddress1;
        public string EmailAddress2;
        public int DepartmentId;
        public string DepartmentDescription;
        public int SupervisorId;
        public string SupervisorName;
        public string Telephone1;
        public string Telephone2;
        public bool IsExternal;
        public IList<Role> Roles;
        public IList<object> Sites;
        public IList<object> SitesResponsibilities;
        public DateTime CreatedDateTime;
        public DateTime LastUpdatedDateTime;
        public string CreatedByPersonId;
        public object CreatedByPersonName;
        public string LastUpdatedByPersonId;
        public object LastUpdatedByPersonName;
        public string Bucket;
        public string Shard;
        public bool IsActive;
        public IList<PersonSiteRelationship> PersonSiteRelationships;
        public string PreferredEmailAddress;
        public string UserIdentifier;
        public int _lsn;
        public Metadata _metadata;

    }
}
