    namespace CosmosWizard.Web.AutoGeneratedFiles
    {
        using System;
        using System.Collections.Generic;

        public class Site
        {
            public class ServiceLine
            {
                public string Key;
                public string Id;
                public string Label;
                public string Value;
            }

            public class Building
            {
                public object EnergyBillPeriods;
                public object EnergyBills;
                public string BuildingCode;
                public string BuildingName;
                public string AddressLine1;
                public string AddressLine2;
                public string City;
                public string County;
                public string PostCode;
                public string Country;
                public string IsoCountryCode;
                public string Region;
                public string ClientFacilityId;
                public double Latitude;
                public double Longitude;
                public int RaisedFloorSpace_SqFt;
                public int TotalSpace_SqFt;
                public int TotalGeneratorPowerCapacity_MW;
                public int UpsPowerCapacity_MW;
                public int ItPowerCapacity_MW;
                public string Facility;
                public object OtherFacility;
                public string Tier;
                public bool IsMasterAddress;
                public string DisplayUnit;
                public object CBRE_Contract_Ref;
                public object TotalDesignLoad_MW;
                public int QuestionnaireResult;
                public string WeatherStationID;
                public double WeatherStationDistanceInMetres;
                public string Bucket;
                public string Shard;
                public string id;
                public object Meta;
            }

            public class Client2
            {
                public string Name;
                public string Bucket;
                public string Shard;
                public string id;
                public object Meta;
            }

            public class Metadata
            {
            }

            public string id;
            public string _rid;
            public string _self;
            public int _ts;
            public string _etag;
            public string SiteCode;
            public string Name;
            public string ClientName;
            public string ClientAndSiteName;
            public IList<ServiceLine> ServiceLines;
            public string CBRE_Contract_Ref;
            public int TotalMainsPowerCapacity;
            public string IsOwnedByClient;
            public string CBRE_Operate_24x7;
            public string Segment;
            public string CMMS;
            public object OtherCMMS;
            public string LineOfBusiness;
            public int NumOfBuildings;
            public IList<Building> Buildings;
            public Client2 Client;
            public IList<string> SiteFeatures;
            public DateTime CreatedDateTime;
            public DateTime LastUpdatedDateTime;
            public string CreatedByPersonId;
            public object CreatedByPersonName;
            public string LastUpdatedByPersonId;
            public object LastUpdatedByPersonName;
            public string Bucket;
            public string Shard;
            public bool IsActive;
            public int _lsn;
            public Metadata _metadata;

        }
    }
